# == DO NOT RENAME THIS FILE ==

# Number of epochs
epoch : 50

# Set batch_size as per your GPU capacity
batch_size : 4

# Tune Model as per your choice/GPU capacity
model :
  d_model : 256 # Dimension of TransformerDecoder's hidden layer
  num_decoder_layers : 4 # Number of Hidden Layers
  nheads : 4 # Number of Heads